# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_token_update:
            pattern:   ^/v2/token/update
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    access_token

        api_token:
            pattern:  ^/v2/token
            stateless: true
            anonymous: true
            form_login:
                check_path:               /v2/token
                require_previous_session: false
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api_webhook:
            pattern:  ^/v2/webhook/
            stateless: true
            anonymous: true

        api_fetch:
          pattern:  ^/v2/fetch/
          stateless: true
          anonymous: true

        api:
            pattern:   ^/v2
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    access_token

    access_control:
            - { path: ^/v2/fetch/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/v2/webhook/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/v2/token/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/v2/admin, role: ROLE_ADMIN }
            - { path: ^/v2, role: IS_AUTHENTICATED_FULLY }
