<?php

namespace AppBundle\Repository;

/**
 * BroadcastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BroadcastRepository extends \Doctrine\ORM\EntityRepository
{
}
