<?php

namespace AppBundle\Repository;

/**
 * CampaignShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignShareRepository extends \Doctrine\ORM\EntityRepository
{
}
