<?php

namespace AppBundle\Repository;

/**
 * CommentRepliesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepliesRepository extends \Doctrine\ORM\EntityRepository
{
}
