<?php

namespace AppBundle\Repository;

/**
 * ConversationMessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationMessagesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $pageID
     * @param $search
     * @return mixed
     */
    public function findMessagesByPageId($pageID, $search){
        $query = $this->createQueryBuilder('cm')
            ->from("AppBundle:Conversation", "c")
            ->from("AppBundle:Subscribers", 's')
            ->select('c.id, c.page_id, s.id as sub_id, s.subscriber_id, s.firstName, s.lastName, s.avatar, cm.items, cm.text, cm.type, cm.created, c.status')
            ->where("c.subscriber = s.id")
            ->andWhere("cm.conversation = c.id")
            ->andWhere("c.page_id = :pageID")
            ->setParameter('pageID', $pageID)
            ->andWhere("cm.type = 1")
            ->andWhere("cm.text LIKE :search")
            ->setParameter("search", "%".$search."%")
            ->orderBy('cm.created', 'DESC');


        return $query->getQuery()->getResult();
    }
}
