<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomFieldsRepository extends EntityRepository
{
    /**
     * @param $pageID
     * @param array $params
     * @return mixed
     */
    public function getAllByPageID($pageID, $params=[]){
        $query = $this->createQueryBuilder('cf')
            ->select('cf')
            ->where("cf.page_id = :pageID")
            ->setParameter('pageID', $pageID);

        if(isset($params['status'])){
            $status = null;
            if(is_bool($params['status'])){
                $status = $params['status'];
            }
            elseif ($params['status'] == "false"){
                $status = false;
            }
            elseif ($params['status'] == "true"){
                $status = true;
            }
            if(!is_null($status) && is_bool($status)){
                $query->andWhere('cf.status = :status')
                    ->setParameter("status", $status);
            }
        }

        if(isset($params['search']) && !empty($params['search'])){
            $query->andWhere('cf.name LIKE :name')
                ->setParameter("name", '%'.$params['search'].'%');
        }

        return $query->getQuery()->getResult();
    }
}
