<?php

namespace AppBundle\Repository;

/**
 * CustomRefParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomRefParameterRepository extends \Doctrine\ORM\EntityRepository
{
}
