<?php

namespace AppBundle\Repository;

/**
 * DefaultReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefaultReplyRepository extends \Doctrine\ORM\EntityRepository
{
}
