<?php

namespace AppBundle\Repository;

/**
 * DefaultReplyLastSendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefaultReplyLastSendRepository extends \Doctrine\ORM\EntityRepository
{
}
