<?php

namespace AppBundle\Repository;

/**
 * DigistoreProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DigistoreProductRepository extends \Doctrine\ORM\EntityRepository
{
}
