<?php

namespace AppBundle\Repository;

/**
 * FlowItemsDraftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlowItemsDraftRepository extends \Doctrine\ORM\EntityRepository
{
}
