<?php

namespace AppBundle\Repository;

/**
 * FlowItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlowItemsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return mixed
     */
    public function updateSentCountById($id){

        return $this->getEntityManager()
            ->createQuery(
                "UPDATE AppBundle:FlowItems fi SET fi.sent = fi.sent+1 WHERE fi.id =".$id
            )
            ->getResult();
    }
}
