<?php

namespace AppBundle\Repository;

/**
 * FoldersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoldersRepository extends \Doctrine\ORM\EntityRepository
{
}
