<?php

namespace AppBundle\Repository;

/**
 * GreetingTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GreetingTextRepository extends \Doctrine\ORM\EntityRepository
{
}
