<?php

namespace AppBundle\Repository;

/**
 * InviteLinkAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InviteLinkAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
