<?php

namespace AppBundle\Repository;

/**
 * MainMenuDraftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainMenuDraftRepository extends \Doctrine\ORM\EntityRepository
{
}
