<?php

namespace AppBundle\Repository;

/**
 * MainMenuItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainMenuItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
