<?php

namespace AppBundle\Repository;

/**
 * MainMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
