<?php

namespace AppBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $params
     * @return mixed
     */
    public function getAllForAdmin($params=[]){
        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->orderBy('p.created','DESC');

        if(isset($params['search']) && !empty($params['search'])){
            $query->andWhere('p.title LIKE :search')
                ->setParameter('search', "%".$params['search']."%");
        }

        if(isset($params['status']) && ($params['status'] == 'false' || $params['status'] == 'true')){
            if($params['status'] == 'false'){
                $query->andWhere('p.status = :status')
                    ->setParameter('status', false);
            }
            elseif ($params['status'] == 'true'){
                $query->andWhere('p.status = :status')
                    ->setParameter('status', true);
            }
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @param $page_id
     */
    public function removeByPageId($page_id){
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Autoposting c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Broadcast c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Conversation c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:CustomFields c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:DefaultReply c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:GreetingText c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:InviteLinkAdmin c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Keywords c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:MainMenu c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Notification c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:PageAdmins c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Sequences c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Subscribers c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Tag c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:WelcomeMessage c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Widget c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Folders c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Flows c WHERE c.page_id='$page_id'"
            )
            ->getResult();
        $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Page c WHERE c.page_id='$page_id'"
            )
            ->getResult();
    }
}
