<?php

namespace AppBundle\Repository;

/**
 * PageShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageShareRepository extends \Doctrine\ORM\EntityRepository
{
}
