<?php

namespace AppBundle\Repository;

/**
 * PageAdminsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageAdminsRepository extends \Doctrine\ORM\EntityRepository
{
}
