<?php

namespace AppBundle\Repository;

/**
 * SaveImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaveImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
