<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Sequences;

/**
 * SequencesItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequencesItemsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Sequences $sequence
     * @param $number
     * @return null
     */
    public function getNextSequencesItem(Sequences $sequence, $number)
    {
        $result = $this->createQueryBuilder('si')
            ->select('si')
            ->where("si.sequence = :sequenceID")
            ->setParameter('sequenceID', $sequence->getId())
            ->andWhere("si.number > :number")
            ->setParameter('number', $number)
            ->andWhere('si.status = :status')
            ->setParameter('status', true)
            ->orderBy('si.number', 'ASC')
            ->getQuery()
            ->getResult();

        return (isset($result[0])) ? $result[0] : null;
    }
}
