<?php

namespace AppBundle\Repository;

/**
 * SequenceShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceShareRepository extends \Doctrine\ORM\EntityRepository
{
}
