<?php

namespace AppBundle\Repository;

/**
 * SubscribersWidgetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribersWidgetsRepository extends \Doctrine\ORM\EntityRepository
{
}
