<?php

namespace AppBundle\Repository;

/**
 * SubscribersTagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribersTagsRepository extends \Doctrine\ORM\EntityRepository
{
}
