<?php

namespace AppBundle\Repository;

/**
 * SubscribersCustomFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribersCustomFieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
