<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Sequences;

/**
 * SubscribersSequencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribersSequencesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Sequences $sequence
     * @return mixed
     */
    public function getAllWithoutLastStageNotProcessed(Sequences $sequence){
        return $this->createQueryBuilder('ss')
            ->select('ss')
            ->where("ss.sequence = :sequenceID")
            ->setParameter('sequenceID', $sequence->getId())
            ->andWhere("ss.stage <> :stage")
            ->setParameter('stage', 'last')
            ->andWhere("ss.processed <> :processed")
            ->setParameter("processed", true)
            ->getQuery()
            ->getResult();
    }
}
