<?php

namespace AppBundle\Repository;

/**
 * UploadAttachmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadAttachmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
