<?php

namespace AppBundle\Repository;

/**
 * UserRefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRefRepository extends \Doctrine\ORM\EntityRepository
{
}
