<?php

namespace AppBundle\Repository;

/**
 * UserInputDelayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInputDelayRepository extends \Doctrine\ORM\EntityRepository
{
}
