<?php

namespace AppBundle\Repository;

/**
 * UserInputResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInputResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
