<?php

namespace AppBundle\Repository;

/**
 * WelcomeMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WelcomeMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
