<?php

namespace AppBundle\Repository;

/**
 * ZapierApiKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZapierApiKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
