<?php

namespace AppBundle\Repository;

/**
 * ZapierWebhookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZapierWebhookRepository extends \Doctrine\ORM\EntityRepository
{
}
